vich_uploader:
    db_driver: orm

    mappings:
        lecture_videos:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/var/videos/originals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        talk_attachments:
            uri_prefix: /uploads/talk_attachments
            upload_destination: '%kernel.project_dir%/public/uploads/talk_attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
